# Generated by Django 5.2.7 on 2025-10-28 07:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('avg_cost_basis', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ticker'], name='trades_hold_user_id_164bff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='holding_qty_nonneg'), models.CheckConstraint(condition=models.Q(('avg_cost_basis__gte', 0)), name='holding_acb_nonneg')],
                'unique_together': {('user', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('ticker', models.CharField(max_length=12)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exec_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exec_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ticker', 'exec_timestamp'], name='trades_trad_user_id_e8733b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('shares__gt', 0)), name='trade_shares_positive'), models.CheckConstraint(condition=models.Q(('exec_price__gt', 0)), name='trade_price_positive')],
            },
        ),
    ]
