# Generated by Django 5.2.7 on 2025-10-28 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holding',
            new_name='Holdings',
        ),
        migrations.RenameModel(
            old_name='Trade',
            new_name='Trades',
        ),
        migrations.RenameIndex(
            model_name='holdings',
            new_name='trades_hold_user_id_3551bc_idx',
            old_name='trades_hold_user_id_164bff_idx',
        ),
        migrations.RenameIndex(
            model_name='trades',
            new_name='trades_trad_user_id_3052a7_idx',
            old_name='trades_trad_user_id_e8733b_idx',
        ),
    ]
