# Generated by Django 5.2.7 on 2025-11-07 01:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='current_cash_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10),
        ),
    ]
