# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNavigatebuy():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_navigatebuy(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1269, 959)
    self.driver.find_element(By.LINK_TEXT, "Buy Stocks").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Sell Stocks").click()
    self.driver.find_element(By.LINK_TEXT, "Buy Stocks").click()
  
